name: Blob storage website CI
      
on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v4

    - name: Install curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        echo "/usr/bin" >> $GITHUB_PATH

    - uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      run: |
        az storage blob upload-batch --overwrite --account-name ${{ secrets.AZURE_RID }} --auth-mode key -d '$web' -s .

    - name: Purge CDN endpoint
      run: |
        az cdn endpoint purge --content-paths "/*" --profile-name "${{ secrets.AZURE_RID }}" --name "${{ secrets.AZURE_RID }}" --resource-group ${{ secrets.AZURE_RSG }}


    # Azure logout
    - name: logout
      run: |
            az logout
      if: always()

    - name: Purge Cloudflare cache
      run: |
            curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKENID }}" -H "Content-Type: application/json" --data '{"purge_everything":true}'
      if: always()
